Thu Sep 19 06:49:44 MSK 2019

diff --git a/utils/fan b/utils/fan
--- a/utils/fan
+++ b/utils/fan
@@ -2,7 +2,7 @@
 
 ## hyphop ##
 
-#= khadas vims - fan control via user mode i2c
+#= khadas vims - fan control via user mode i2c + temp monitor
 #/
 
 #s https://github.com/hyphop/khadas-utils
@@ -11,8 +11,22 @@
 
 HELP(){ echo "khadas vims - fan control \
 USAGE
-    fan [0|1|2|3|min|mid|max|on|off] [--help]
 
+    fan [ 0 | 1 | 2 | 3 ] 	# set fan speed level from 0 - 3
+    fan monitor			# foreground temp monitor 
+    fan bg			# background temp monitor - daemon mode
+    fan kill			# stop all running fan processes
+
+MORE OPTS
+
+    fan [ on | off ]		# on off fan same as 1 0
+    fan [ low | middle | max ]	# fan level  same as 1 2 3
+    fan help			# print help
+
+NOTE
+
+    * if fan running as daemon plz dont use manual modes at same time
+    * this fan utilies writed for tests - and works without any waranty!!!
 
 ";}
 
@@ -20,6 +34,35 @@ A=0x18
 C=0x88
 B=
 b=
+
+CMD=
+
+LEVEL_ERROR=-100
+LEVEL0=50000
+LEVEL1=60000
+LEVEL2=70000
+LEVEL3=80000
+
+DELTA=1000
+DELAY=3
+DEFAULT=1
+
+
+INFO(){
+echo "[i] CONSTATS 
+
+LEVEL_ERROR=$LEVEL_ERROR
+LEVEL0=$LEVEL0
+LEVEL1=$LEVEL1
+LEVEL2=$LEVEL2
+LEVEL3=$LEVEV3
+
+DELTA=$DELTA
+DELAY=$DELAY
+DEFAULT=$DEFAULT
+
+"
+}
 
 CMD(){
     echo "[#] $@">&2
@@ -32,6 +75,8 @@ which i2cget 1>/dev/null 2>/dev/null || {
 }
 
 OK=
+LOG=/var/log/fan.log
+
 # check i2c bus
 for B in /dev/i2c-?; do
     [ -c $B ] || {
@@ -39,7 +84,7 @@ for B in /dev/i2c-?; do
 	exit 1
     }
     b=${B#*-}
-    i2cget -y -f $b $A 1>/dev/null && {
+    CMD i2cget -y -f $b $A 1>/dev/null 2>/dev/null && {
 	OK=1
     	break
     }
@@ -57,12 +102,13 @@ GET(){
 }
 
 
+fan_state=
+
 SET(){
-    CMD i2cset -y $b $A $C $1 b
+    fan_state=$1
+    $CMD i2cset -y $b $A $C $1 b
     echo "[i] set FUN SPEED: $1">&2
 }
-
-DEFAULT=1
 
 #echo "[i] $(GET)">&2
 
@@ -71,10 +117,97 @@ DEFAULT=1
     exit 1
 }
 
+
+AUTO(){
+
+    T=
+    for T in /sys/class/thermal/thermal_zone?/temp; do
+	[ -f $T ] && break
+    done
+
+    [ "$T" ] || {
+	echo "[e] temp sensor not found">&2
+	exit 1
+    }
+
+    ON=
+
+    echo "[i] fan on/off test for 1 sec">&2
+    SET 3
+    sleep 1
+    SET 0
+    echo "[i] OK - goto auto LOOP mode">&2
+
+    while [ "1" ] ; do
+    while read t ; do
+
+	echo "[i] temp: $t // fan state: $fan_state">&2
+
+	[ "$t" -lt $LEVEL_ERROR ] && {
+	    echo "[w] temp senson error">&2
+	    continue
+	}
+
+	[ "$t" -lt $LEVEL0 ] && {
+	    [ "$fan_state" = "0" ] || \
+	    SET 0
+	    continue
+	}
+
+	[ "$t" -lt $LEVEL1 ] && {
+	    [ "$t" -gt $((LEVEL0+$DELTA)) ] && {
+	    [ "$fan_state" = "1" ] || \
+	    SET 1
+	    }
+	    continue
+	}
+
+	[ "$t" -lt $LEVEL2 ] && {
+	    [ "$t" -gt $((LEVEL1+$DELTA)) ] && {
+	    [ "$fan_state" = "2" ] || \
+	    SET 2
+	    }
+	    continue
+	}
+
+	[ "$t" -lt $LEVEL3 ] && {
+	    [ "$t" -gt $((LEVEL2+$DELTA)) ] && {
+	    [ "$fan_state" = "3" ] || \
+	    SET 3
+	    }
+	    continue
+	}
+
+	echo "[e] overheat !!!!">&2
+
+    done < $T
+	sleep $DELAY
+    done
+
+}
+
 for a in $@; do
 case $a in
     on|e*)
     SET $DEFAULT
+    ;;
+    get|state)
+    GET
+    ;;
+    kill)
+    SET 0
+    echo "[i] kill bg fan process"
+    CMD pkill -f "/fan "
+    ;;
+
+    mon*)
+    AUTO
+    ;;
+    daemon|bg)
+
+    AUTO </dev/null 1>$LOG 2>&1 &
+    echo "[i] start in bg mode - as $!">&2
+
     ;;
     1|2|3)
     SET $a
@@ -90,6 +223,9 @@ case $a in
     ;;
     of*|0|d*)
     SET 0
+    ;;
+    inf*)
+    INFO
     ;;
     *)
     HELP
